name: Node.js CI

on: [push]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install yarn
        run: npm install yarn@1.22.11 -g --force
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
